# Form implementation generated from reading ui file '/Volumes/Data/K25411_KTLT/SmartLockUEL/ui/BookingDialog.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BookingDialog(object):
    def setupUi(self, BookingDialog):
        BookingDialog.setObjectName("BookingDialog")
        BookingDialog.resize(450, 520)
        BookingDialog.setStyleSheet("QDialog { background: white; }\n"
"QLabel { color: #333; }")
        self.mainLayout = QtWidgets.QVBoxLayout(BookingDialog)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.lblTitle = QtWidgets.QLabel(parent=BookingDialog)
        self.lblTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #1F4F82;")
        self.lblTitle.setObjectName("lblTitle")
        self.mainLayout.addWidget(self.lblTitle)
        self.separator = QtWidgets.QFrame(parent=BookingDialog)
        self.separator.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator.setStyleSheet("color: #E3EAF2;")
        self.separator.setObjectName("separator")
        self.mainLayout.addWidget(self.separator)
        self.lblRoom = QtWidgets.QLabel(parent=BookingDialog)
        self.lblRoom.setStyleSheet("font-weight: 600; font-size: 13px;")
        self.lblRoom.setObjectName("lblRoom")
        self.mainLayout.addWidget(self.lblRoom)
        self.comboRoom = QtWidgets.QComboBox(parent=BookingDialog)
        self.comboRoom.setStyleSheet("QComboBox { padding: 8px; border: 1px solid #ddd; border-radius: 8px; font-size: 13px; color: #333; background: white; }\n"
"QComboBox:focus { border: 1px solid #1F4F82; }")
        self.comboRoom.setObjectName("comboRoom")
        self.mainLayout.addWidget(self.comboRoom)
        self.lblSession = QtWidgets.QLabel(parent=BookingDialog)
        self.lblSession.setStyleSheet("font-weight: 600; font-size: 13px;")
        self.lblSession.setObjectName("lblSession")
        self.mainLayout.addWidget(self.lblSession)
        self.sessionGrid = QtWidgets.QGridLayout()
        self.sessionGrid.setSpacing(8)
        self.sessionGrid.setObjectName("sessionGrid")
        self.btnCa1 = QtWidgets.QPushButton(parent=BookingDialog)
        self.btnCa1.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCa1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCa1.setStyleSheet("QPushButton { background: #F5F7FA; border: 2px solid #E3EAF2; border-radius: 10px; padding: 10px 6px; color: #555; font-size: 12px; }\n"
"QPushButton:hover { border-color: #1F4F82; background: #EBF0F7; }")
        self.btnCa1.setObjectName("btnCa1")
        self.sessionGrid.addWidget(self.btnCa1, 0, 0, 1, 1)
        self.btnCa2 = QtWidgets.QPushButton(parent=BookingDialog)
        self.btnCa2.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCa2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCa2.setStyleSheet("QPushButton { background: #F5F7FA; border: 2px solid #E3EAF2; border-radius: 10px; padding: 10px 6px; color: #555; font-size: 12px; }\n"
"QPushButton:hover { border-color: #1F4F82; background: #EBF0F7; }")
        self.btnCa2.setObjectName("btnCa2")
        self.sessionGrid.addWidget(self.btnCa2, 0, 1, 1, 1)
        self.btnCa3 = QtWidgets.QPushButton(parent=BookingDialog)
        self.btnCa3.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCa3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCa3.setStyleSheet("QPushButton { background: #F5F7FA; border: 2px solid #E3EAF2; border-radius: 10px; padding: 10px 6px; color: #555; font-size: 12px; }\n"
"QPushButton:hover { border-color: #1F4F82; background: #EBF0F7; }")
        self.btnCa3.setObjectName("btnCa3")
        self.sessionGrid.addWidget(self.btnCa3, 1, 0, 1, 1)
        self.btnCa4 = QtWidgets.QPushButton(parent=BookingDialog)
        self.btnCa4.setMinimumSize(QtCore.QSize(0, 50))
        self.btnCa4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnCa4.setStyleSheet("QPushButton { background: #F5F7FA; border: 2px solid #E3EAF2; border-radius: 10px; padding: 10px 6px; color: #555; font-size: 12px; }\n"
"QPushButton:hover { border-color: #1F4F82; background: #EBF0F7; }")
        self.btnCa4.setObjectName("btnCa4")
        self.sessionGrid.addWidget(self.btnCa4, 1, 1, 1, 1)
        self.mainLayout.addLayout(self.sessionGrid)
        self.lblReason = QtWidgets.QLabel(parent=BookingDialog)
        self.lblReason.setStyleSheet("font-weight: 600; font-size: 13px;")
        self.lblReason.setObjectName("lblReason")
        self.mainLayout.addWidget(self.lblReason)
        self.txtReason = QtWidgets.QTextEdit(parent=BookingDialog)
        self.txtReason.setMaximumSize(QtCore.QSize(16777215, 70))
        self.txtReason.setStyleSheet("QTextEdit { border: 1px solid #ddd; border-radius: 8px; padding: 6px; font-size: 13px; color: #333; }\n"
"QTextEdit:focus { border: 1px solid #1F4F82; }")
        self.txtReason.setObjectName("txtReason")
        self.mainLayout.addWidget(self.txtReason)
        self.btnLayout = QtWidgets.QHBoxLayout()
        self.btnLayout.setSpacing(10)
        self.btnLayout.setObjectName("btnLayout")
        self.btnCancel = QtWidgets.QPushButton(parent=BookingDialog)
        self.btnCancel.setStyleSheet("QPushButton { background: #F5F5F5; border: 1px solid #ddd; border-radius: 8px; padding: 8px 20px; color: #666; font-size: 13px; }\n"
"QPushButton:hover { background: #E0E0E0; }")
        self.btnCancel.setObjectName("btnCancel")
        self.btnLayout.addWidget(self.btnCancel)
        self.btnSubmit = QtWidgets.QPushButton(parent=BookingDialog)
        self.btnSubmit.setStyleSheet("QPushButton { background: #1F4F82; border: none; border-radius: 8px; padding: 8px 20px; color: white; font-size: 13px; font-weight: bold; }\n"
"QPushButton:hover { background: #163D66; }")
        self.btnSubmit.setObjectName("btnSubmit")
        self.btnLayout.addWidget(self.btnSubmit)
        self.mainLayout.addLayout(self.btnLayout)

        self.retranslateUi(BookingDialog)
        QtCore.QMetaObject.connectSlotsByName(BookingDialog)

    def retranslateUi(self, BookingDialog):
        _translate = QtCore.QCoreApplication.translate
        BookingDialog.setWindowTitle(_translate("BookingDialog", "Đặt phòng"))
        self.lblTitle.setText(_translate("BookingDialog", "Đặt phòng"))
        self.lblRoom.setText(_translate("BookingDialog", "Chọn phòng:"))
        self.lblSession.setText(_translate("BookingDialog", "Select sessions (multiple allowed):"))
        self.btnCa1.setText(_translate("BookingDialog", "Session 1\n"
"07:00 – 09:30"))
        self.btnCa2.setText(_translate("BookingDialog", "Session 2\n"
"09:45 – 12:15"))
        self.btnCa3.setText(_translate("BookingDialog", "Session 3\n"
"12:30 – 15:00"))
        self.btnCa4.setText(_translate("BookingDialog", "Session 4\n"
"15:15 – 17:45"))
        self.lblReason.setText(_translate("BookingDialog", "Lý do:"))
        self.txtReason.setPlaceholderText(_translate("BookingDialog", "Họp nhóm, sinh hoạt CLB, tự học, dạy bù, hội thảo..."))
        self.btnCancel.setText(_translate("BookingDialog", "Hủy"))
        self.btnSubmit.setText(_translate("BookingDialog", "Xác nhận đặt phòng"))
