# Form implementation generated from reading ui file '/Volumes/Data/K25411_KTLT/SmartLockUEL/ui/BookingHistory.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BookingHistory(object):
    def setupUi(self, BookingHistory):
        BookingHistory.setObjectName("BookingHistory")
        BookingHistory.resize(700, 500)
        BookingHistory.setStyleSheet("QDialog { background: #F5F7FA; }\n"
"QLabel { color: #333; border: none; }\n"
"QTableWidget { background: white; border: 1px solid #E3EAF2; border-radius: 8px; gridline-color: #F0F0F0; font-size: 12px; color: #333; }\n"
"QTableWidget::item { padding: 6px; color: #333; }\n"
"QHeaderView::section { background: #1F4F82; color: white; font-weight: bold; font-size: 12px; padding: 8px; border: none; }\n"
"QScrollBar:vertical { width: 8px; background: #F0F0F0; border-radius: 4px; }\n"
"QScrollBar::handle:vertical { background: #C0C0C0; border-radius: 4px; }")
        self.mainLayout = QtWidgets.QVBoxLayout(BookingHistory)
        self.mainLayout.setContentsMargins(20, 20, 20, 20)
        self.mainLayout.setSpacing(12)
        self.mainLayout.setObjectName("mainLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setSpacing(0)
        self.headerLayout.setObjectName("headerLayout")
        self.lblTitle = QtWidgets.QLabel(parent=BookingHistory)
        self.lblTitle.setStyleSheet("font-size: 18px; font-weight: bold; color: #1F4F82;")
        self.lblTitle.setObjectName("lblTitle")
        self.headerLayout.addWidget(self.lblTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem)
        self.comboFilter = QtWidgets.QComboBox(parent=BookingHistory)
        self.comboFilter.setMinimumSize(QtCore.QSize(130, 32))
        self.comboFilter.setStyleSheet("QComboBox { padding: 4px 10px; border: 1px solid #ddd; border-radius: 6px; font-size: 12px; background: white; color: #333; }\n"
"QComboBox:focus { border: 1px solid #1F4F82; }")
        self.comboFilter.setObjectName("comboFilter")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.comboFilter.addItem("")
        self.headerLayout.addWidget(self.comboFilter)
        self.mainLayout.addLayout(self.headerLayout)
        self.separator = QtWidgets.QFrame(parent=BookingHistory)
        self.separator.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.separator.setStyleSheet("color: #E3EAF2;")
        self.separator.setObjectName("separator")
        self.mainLayout.addWidget(self.separator)
        self.tableHistory = QtWidgets.QTableWidget(parent=BookingHistory)
        self.tableHistory.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableHistory.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableHistory.setAlternatingRowColors(True)
        self.tableHistory.setShowGrid(False)
        self.tableHistory.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.tableHistory.setObjectName("tableHistory")
        self.tableHistory.setColumnCount(7)
        self.tableHistory.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableHistory.setHorizontalHeaderItem(6, item)
        self.mainLayout.addWidget(self.tableHistory)
        self.footerLayout = QtWidgets.QHBoxLayout()
        self.footerLayout.setSpacing(0)
        self.footerLayout.setObjectName("footerLayout")
        self.lblCount = QtWidgets.QLabel(parent=BookingHistory)
        self.lblCount.setStyleSheet("color: #888; font-size: 11px;")
        self.lblCount.setObjectName("lblCount")
        self.footerLayout.addWidget(self.lblCount)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.footerLayout.addItem(spacerItem1)
        self.btnClose = QtWidgets.QPushButton(parent=BookingHistory)
        self.btnClose.setMinimumSize(QtCore.QSize(90, 34))
        self.btnClose.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btnClose.setStyleSheet("QPushButton { background: #1F4F82; border: none; border-radius: 8px; padding: 6px 20px; color: white; font-size: 13px; font-weight: bold; }\n"
"QPushButton:hover { background: #163D66; }")
        self.btnClose.setObjectName("btnClose")
        self.footerLayout.addWidget(self.btnClose)
        self.mainLayout.addLayout(self.footerLayout)

        self.retranslateUi(BookingHistory)
        QtCore.QMetaObject.connectSlotsByName(BookingHistory)

    def retranslateUi(self, BookingHistory):
        _translate = QtCore.QCoreApplication.translate
        BookingHistory.setWindowTitle(_translate("BookingHistory", "Booking History"))
        self.lblTitle.setText(_translate("BookingHistory", "Booking History"))
        self.comboFilter.setItemText(0, _translate("BookingHistory", "All Status"))
        self.comboFilter.setItemText(1, _translate("BookingHistory", "Pending"))
        self.comboFilter.setItemText(2, _translate("BookingHistory", "Approved"))
        self.comboFilter.setItemText(3, _translate("BookingHistory", "Rejected"))
        item = self.tableHistory.horizontalHeaderItem(0)
        item.setText(_translate("BookingHistory", "Room"))
        item = self.tableHistory.horizontalHeaderItem(1)
        item.setText(_translate("BookingHistory", "Type"))
        item = self.tableHistory.horizontalHeaderItem(2)
        item.setText(_translate("BookingHistory", "Session"))
        item = self.tableHistory.horizontalHeaderItem(3)
        item.setText(_translate("BookingHistory", "Reason"))
        item = self.tableHistory.horizontalHeaderItem(4)
        item.setText(_translate("BookingHistory", "Status"))
        item = self.tableHistory.horizontalHeaderItem(5)
        item.setText(_translate("BookingHistory", "Locker Password"))
        item = self.tableHistory.horizontalHeaderItem(6)
        item.setText(_translate("BookingHistory", "Action"))
        self.lblCount.setText(_translate("BookingHistory", "0 bookings"))
        self.btnClose.setText(_translate("BookingHistory", "Close"))
