# Form implementation generated from reading ui file '/Volumes/Data/K25411_KTLT/SmartLockUEL/ui/Login.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1237, 734)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-image: url(:/newPrefix/background.jpg);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, -1)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_17.addItem(spacerItem)
        self.gridLayout_2.addLayout(self.verticalLayout_17, 4, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(400, 380))
        self.widget.setMaximumSize(QtCore.QSize(400, 380))
        self.widget.setStyleSheet("#framePasswordContainer {\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"#framePasswordContainer:focus-within {\n"
"    border: 1px solid #1f4f82;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setEnabled(True)
        self.label.setMinimumSize(QtCore.QSize(125, 125))
        self.label.setMaximumSize(QtCore.QSize(125, 125))
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("/Volumes/Data/K25411_KTLT/SmartLockUEL/ui/../images/UEL_Logo.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setStyleSheet("color: #003F87")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lineEditEmail = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEditEmail.setStyleSheet("QLineEdit {border: 1px solid #dcdcdc;\n"
"    color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"padding: 8px; \n"
"font-size: 13px;}\n"
"QLineEdit:focus {border: 1px solid #1f4f82;}\n"
"QLineEdit::placeholder { color: #9aa0a6;}\n"
"")
        self.lineEditEmail.setClearButtonEnabled(True)
        self.lineEditEmail.setObjectName("lineEditEmail")
        self.verticalLayout.addWidget(self.lineEditEmail)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setStyleSheet(" color:#003F87")
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.frame = QtWidgets.QFrame(parent=self.widget)
        self.frame.setStyleSheet("#framePasswordContainer {\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"#framePasswordContainer:focus-within {\n"
"    border: 1px solid #1f4f82;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEditPassword.setStyleSheet("#lineEditPassword {\n"
"    color: rgb(0, 0, 0);\n"
"    border: none; \n"
"    background: transparent; \n"
"    padding: 8px; \n"
"    font-size: 13px;\n"
"}")
        self.lineEditPassword.setMaxLength(32772)
        self.lineEditPassword.setFrame(True)
        self.lineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.lineEditPassword.setDragEnabled(False)
        self.lineEditPassword.setClearButtonEnabled(False)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.horizontalLayout_2.addWidget(self.lineEditPassword)
        self.btnTogglePassword = QtWidgets.QPushButton(parent=self.frame)
        self.btnTogglePassword.setStyleSheet("#btnTogglePassword {\n"
"    border: none;\n"
"    background: transparent;\n"
"}")
        self.btnTogglePassword.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Volumes/Data/K25411_KTLT/SmartLockUEL/ui/D:/Nam1/HK2/LapTrinh/Group/eye_closed.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnTogglePassword.setIcon(icon)
        self.btnTogglePassword.setIconSize(QtCore.QSize(30, 30))
        self.btnTogglePassword.setFlat(True)
        self.btnTogglePassword.setObjectName("btnTogglePassword")
        self.horizontalLayout_2.addWidget(self.btnTogglePassword)
        self.verticalLayout.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButtonUser = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButtonUser.setMinimumSize(QtCore.QSize(0, 10))
        self.radioButtonUser.setStyleSheet("color: #003F87;\n"
"font-size: 13px;\n"
"spacing: 8px\n"
"")
        self.radioButtonUser.setChecked(False)
        self.radioButtonUser.setObjectName("radioButtonUser")
        self.horizontalLayout.addWidget(self.radioButtonUser)
        self.radioButtonAdmin = QtWidgets.QRadioButton(parent=self.widget)
        self.radioButtonAdmin.setStyleSheet("color: #003F87;\n"
"font-size: 13px;\n"
"spacing: 8px")
        self.radioButtonAdmin.setChecked(True)
        self.radioButtonAdmin.setObjectName("radioButtonAdmin")
        self.horizontalLayout.addWidget(self.radioButtonAdmin)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.pushButtonLogin = QtWidgets.QPushButton(parent=self.widget)
        self.pushButtonLogin.setStyleSheet("QPushButton{background-color: #1f4f82;\n"
"color: white;\n"
"border-radius: 8px;\n"
"height: 35px}\n"
"QPushButton:hover {background-color: #f26522}\n"
"QPushButton:pressed {background-color: #ffb347}\n"
"")
        self.pushButtonLogin.setObjectName("pushButtonLogin")
        self.verticalLayout_3.addWidget(self.pushButtonLogin)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_10.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.verticalLayout_10, 2, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_2.setStyleSheet("background-color: #1f4f82;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Baskerville Old Face")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_11.addWidget(self.label_2)
        self.gridLayout_2.addWidget(self.frame_2, 0, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout()
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_8.setMinimumSize(QtCore.QSize(0, 30))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_8.setStyleSheet("color:#003F87;\n"
"font-size:12px;\n"
"font-weight:600;\n"
"padding:8px 0px;")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_19.addWidget(self.label_8)
        self.frame_6 = QtWidgets.QFrame(parent=self.frame_5)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 1))
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_19.addWidget(self.frame_6)
        self.verticalLayout_24.addLayout(self.verticalLayout_19)
        self.gridLayout_2.addWidget(self.frame_5, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Email:"))
        self.lineEditEmail.setText(_translate("MainWindow", "sv001@st.uel.edu.vn"))
        self.lineEditEmail.setPlaceholderText(_translate("MainWindow", "example@st.uel.edu.vn/example@uel.edu.vn  "))
        self.label_4.setText(_translate("MainWindow", "Password:"))
        self.lineEditPassword.setText(_translate("MainWindow", "123456"))
        self.lineEditPassword.setPlaceholderText(_translate("MainWindow", "Nhập mật khẩu "))
        self.radioButtonUser.setText(_translate("MainWindow", "Lecturer/Student"))
        self.radioButtonAdmin.setText(_translate("MainWindow", "Administrator"))
        self.pushButtonLogin.setText(_translate("MainWindow", "Đăng nhập"))
        self.label_2.setText(_translate("MainWindow", "SmartStock UEL"))
        self.label_8.setText(_translate("MainWindow", "Trường Đại học Kinh tế – Luật, Đại học Quốc gia Thành phố Hồ Chí Minh"))
