# Form implementation generated from reading ui file '/Volumes/Data/K25411_KTLT/SmartLockUEL/ui/navbar.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NavBar(object):
    def setupUi(self, NavBar):
        NavBar.setObjectName("NavBar")
        NavBar.resize(800, 80)
        NavBar.setMinimumSize(QtCore.QSize(0, 80))
        NavBar.setMaximumSize(QtCore.QSize(16777215, 80))
        NavBar.setStyleSheet("background-color: #1f4f82;")
        NavBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.horizontalLayout = QtWidgets.QHBoxLayout(NavBar)
        self.horizontalLayout.setContentsMargins(15, -1, 15, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelTitle = QtWidgets.QLabel(parent=NavBar)
        self.labelTitle.setStyleSheet("color: white; font-size: 16pt; font-weight: bold;")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout.addWidget(self.labelTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lineEditSearch = QtWidgets.QLineEdit(parent=NavBar)
        self.lineEditSearch.setMinimumSize(QtCore.QSize(150, 0))
        self.lineEditSearch.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEditSearch.setStyleSheet("QLineEdit {\n"
"    background-color: white;\n"
"    border: 1px solid #B0BEC5;\n"
"    border-radius: 15px;\n"
"    padding: 5px 10px;\n"
"    color: black;\n"
"}\n"
"QLineEdit::placeholder {\n"
"    color: #9aa0a6;\n"
"}")
        self.lineEditSearch.setObjectName("lineEditSearch")
        self.horizontalLayout.addWidget(self.lineEditSearch)
        self.btnRole = QtWidgets.QPushButton(parent=NavBar)
        self.btnRole.setStyleSheet("QPushButton {\n"
"    background-color: white;\n"
"    color: #1F4F82;\n"
"    border: 1.5px solid #1F4F82;\n"
"    border-radius: 8px;\n"
"    padding: 6px 18px;\n"
"    font-weight: 600;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #1F4F82;\n"
"    color: white;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #163B63;\n"
"    color: white;\n"
"}")
        self.btnRole.setObjectName("btnRole")
        self.horizontalLayout.addWidget(self.btnRole)
        self.btnLang = QtWidgets.QPushButton(parent=NavBar)
        self.btnLang.setMinimumSize(QtCore.QSize(40, 0))
        self.btnLang.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: white;\n"
"    border: 1.5px solid rgba(255,255,255,0.6);\n"
"    border-radius: 8px;\n"
"    padding: 6px 12px;\n"
"    font-weight: 600;\n"
"    font-size: 12px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255,255,255,0.15);\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: rgba(255,255,255,0.25);\n"
"}")
        self.btnLang.setObjectName("btnLang")
        self.horizontalLayout.addWidget(self.btnLang)

        self.retranslateUi(NavBar)
        QtCore.QMetaObject.connectSlotsByName(NavBar)

    def retranslateUi(self, NavBar):
        _translate = QtCore.QCoreApplication.translate
        self.labelTitle.setText(_translate("NavBar", "SmartLocker UEL"))
        self.lineEditSearch.setPlaceholderText(_translate("NavBar", "Search..."))
        self.btnRole.setText(_translate("NavBar", "Admin"))
        self.btnLang.setText(_translate("NavBar", "VI"))
