# Form implementation generated from reading ui file '/Volumes/Data/K25411_KTLT/SmartLockUEL/ui/OverviewAdmin.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_OverviewAdminContent(object):
    def setupUi(self, OverviewAdminContent):
        OverviewAdminContent.setObjectName("OverviewAdminContent")
        OverviewAdminContent.setStyleSheet("background-color: #F5F8FC;")
        self.verticalLayout = QtWidgets.QVBoxLayout(OverviewAdminContent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.btnAll = QtWidgets.QPushButton(parent=OverviewAdminContent)
        self.btnAll.setMinimumSize(QtCore.QSize(0, 35))
        self.btnAll.setStyleSheet("QPushButton{background-color:#E3F2FD;border:1px solid #1565C0;border-radius:15px;padding:6px 15px;color:#0D47A1;font-weight:500;}QPushButton:checked{background-color:#1565C0;color:white;}QPushButton:hover{background-color:#1E88E5;color:white;}")
        self.btnAll.setCheckable(True)
        self.btnAll.setAutoExclusive(True)
        self.btnAll.setObjectName("btnAll")
        self.filterLayout.addWidget(self.btnAll)
        self.btnAvailable = QtWidgets.QPushButton(parent=OverviewAdminContent)
        self.btnAvailable.setMinimumSize(QtCore.QSize(0, 35))
        self.btnAvailable.setStyleSheet("QPushButton{background-color:#E8F5E9;border:1px solid #1565C0;border-radius:15px;padding:6px 15px;color:#0D47A1;font-weight:500;}QPushButton:checked{background-color:#1565C0;color:white;}QPushButton:hover{background-color:#1E88E5;color:white;}")
        self.btnAvailable.setCheckable(True)
        self.btnAvailable.setAutoExclusive(True)
        self.btnAvailable.setObjectName("btnAvailable")
        self.filterLayout.addWidget(self.btnAvailable)
        self.btnOccupied = QtWidgets.QPushButton(parent=OverviewAdminContent)
        self.btnOccupied.setMinimumSize(QtCore.QSize(0, 35))
        self.btnOccupied.setStyleSheet("QPushButton{background-color:#FFEBEE;border:1px solid #1565C0;border-radius:15px;padding:6px 15px;color:#0D47A1;font-weight:500;}QPushButton:checked{background-color:#1565C0;color:white;}QPushButton:hover{background-color:#1E88E5;color:white;}")
        self.btnOccupied.setCheckable(True)
        self.btnOccupied.setAutoExclusive(True)
        self.btnOccupied.setObjectName("btnOccupied")
        self.filterLayout.addWidget(self.btnOccupied)
        self.btnBooked = QtWidgets.QPushButton(parent=OverviewAdminContent)
        self.btnBooked.setMinimumSize(QtCore.QSize(0, 35))
        self.btnBooked.setStyleSheet("QPushButton{background-color:#FFF8E1;border:1px solid #1565C0;border-radius:15px;padding:6px 15px;color:#0D47A1;font-weight:500;}QPushButton:checked{background-color:#1565C0;color:white;}QPushButton:hover{background-color:#1E88E5;color:white;}")
        self.btnBooked.setCheckable(True)
        self.btnBooked.setAutoExclusive(True)
        self.btnBooked.setObjectName("btnBooked")
        self.filterLayout.addWidget(self.btnBooked)
        self.btnCleaning = QtWidgets.QPushButton(parent=OverviewAdminContent)
        self.btnCleaning.setMinimumSize(QtCore.QSize(0, 35))
        self.btnCleaning.setStyleSheet("QPushButton{background-color:#E3F2FD;border:1px solid #1565C0;border-radius:15px;padding:6px 15px;color:#0D47A1;font-weight:500;}QPushButton:checked{background-color:#1565C0;color:white;}QPushButton:hover{background-color:#1E88E5;color:white;}")
        self.btnCleaning.setCheckable(True)
        self.btnCleaning.setAutoExclusive(True)
        self.btnCleaning.setObjectName("btnCleaning")
        self.filterLayout.addWidget(self.btnCleaning)
        self.verticalLayout.addLayout(self.filterLayout)
        self.scrollArea = QtWidgets.QScrollArea(parent=OverviewAdminContent)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.widgetRooms = QtWidgets.QWidget()
        self.widgetRooms.setObjectName("widgetRooms")
        self.gridLayout = QtWidgets.QGridLayout(self.widgetRooms)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.widgetRooms)
        self.verticalLayout.addWidget(self.scrollArea)

        self.retranslateUi(OverviewAdminContent)
        QtCore.QMetaObject.connectSlotsByName(OverviewAdminContent)

    def retranslateUi(self, OverviewAdminContent):
        _translate = QtCore.QCoreApplication.translate
        self.btnAll.setText(_translate("OverviewAdminContent", "All"))
        self.btnAvailable.setText(_translate("OverviewAdminContent", "Available"))
        self.btnOccupied.setText(_translate("OverviewAdminContent", "Occupied"))
        self.btnBooked.setText(_translate("OverviewAdminContent", "Full"))
        self.btnCleaning.setText(_translate("OverviewAdminContent", "Cleaning"))
