# Form implementation generated from reading ui file '/Volumes/Data/K25411_KTLT/SmartLockUEL/ui/sidebar.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SideBar(object):
    def setupUi(self, SideBar):
        SideBar.setObjectName("SideBar")
        SideBar.resize(220, 500)
        SideBar.setMinimumSize(QtCore.QSize(180, 0))
        SideBar.setMaximumSize(QtCore.QSize(260, 16777215))
        SideBar.setStyleSheet("QFrame {\n"
"    background-color: #DCE3EC;\n"
"}\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: #0B2545;\n"
"    text-align: left;\n"
"    padding: 12px;\n"
"    font-size: 16px;\n"
"    border: none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255,255,255,0.2);\n"
"}")
        SideBar.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.verticalLayout = QtWidgets.QVBoxLayout(SideBar)
        self.verticalLayout.setContentsMargins(8, 8, 8, 8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonOverview = QtWidgets.QPushButton(parent=SideBar)
        self.pushButtonOverview.setObjectName("pushButtonOverview")
        self.verticalLayout.addWidget(self.pushButtonOverview)
        self.pushButtonBookings = QtWidgets.QPushButton(parent=SideBar)
        self.pushButtonBookings.setObjectName("pushButtonBookings")
        self.verticalLayout.addWidget(self.pushButtonBookings)
        self.pushButtonEdit = QtWidgets.QPushButton(parent=SideBar)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.verticalLayout.addWidget(self.pushButtonEdit)
        self.pushButtonUsers = QtWidgets.QPushButton(parent=SideBar)
        self.pushButtonUsers.setObjectName("pushButtonUsers")
        self.verticalLayout.addWidget(self.pushButtonUsers)
        self.pushButtonDevices = QtWidgets.QPushButton(parent=SideBar)
        self.pushButtonDevices.setObjectName("pushButtonDevices")
        self.verticalLayout.addWidget(self.pushButtonDevices)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButtonLogOut = QtWidgets.QPushButton(parent=SideBar)
        self.pushButtonLogOut.setObjectName("pushButtonLogOut")
        self.verticalLayout.addWidget(self.pushButtonLogOut)
        self.pushButtonQuit = QtWidgets.QPushButton(parent=SideBar)
        self.pushButtonQuit.setObjectName("pushButtonQuit")
        self.verticalLayout.addWidget(self.pushButtonQuit)

        self.retranslateUi(SideBar)
        QtCore.QMetaObject.connectSlotsByName(SideBar)

    def retranslateUi(self, SideBar):
        _translate = QtCore.QCoreApplication.translate
        self.pushButtonOverview.setText(_translate("SideBar", "Dashboard"))
        self.pushButtonBookings.setText(_translate("SideBar", "Booking Management"))
        self.pushButtonEdit.setText(_translate("SideBar", "Room Management"))
        self.pushButtonUsers.setText(_translate("SideBar", "Users Management"))
        self.pushButtonDevices.setText(_translate("SideBar", "Devices Management"))
        self.pushButtonLogOut.setText(_translate("SideBar", "Log out"))
        self.pushButtonQuit.setText(_translate("SideBar", "Quit"))
